name: CI

on: push

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: latest
      - uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Solfacil
          password: ${{ secrets.REGISTRY_PERSONAL_TOKEN }}

      - name: pipeline
        run: earthly -P --ci +all

